on:
  push:
    branch:
      - master

jobs:
  build:
    name: cicd
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: version
        run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
        id: version
      - name: commit subjects
        id: commit_subjects
        run: |
          FIRSTTEST="this is the first test"
          SECONDTEST=$(git log --oneline -1)
          COMMITS=$(git log --pretty=%s $(git describe --abbrev=0 --tags 2> /dev/null || git log --reverse --oneline --pretty=%h | head -n 1)..HEAD | xargs -r -n 1 -d '\n' echo \*)
          echo $COMMITS
          echo $FIRSTTEST
          echo $SECONDTEST
          echo "::set-output name=commits::$COMMITS"
      - name: echo version
        run: echo ${{ steps.version.outputs.version }}
      - name: echo commits
        run: echo ${{ steps.commit_subjects.outputs.commits }}
        #- name: release
        #  uses: actions/create-release@v1
        #  with:
        #    draft: false
        #    prerelease: false
        #    release_name: ${{ steps.version.outputs.version }}
        #    tag_name: ${{ steps.version.outputs.version }}
        #    body: ${{ 
        #  env:
        #    GITHUB_TOKEN: ${{ github.token }}
