on:
  push:
    branch:
      - master

jobs:
  build:
    name: cicd
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}-${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
