on:
  push:
    branch:
      - master

jobs:
  build:
    name: cicd
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: version
        run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
        id: version
      - name: echo version
        run: echo ${{ steps.version.outputs.version }}
        #       - name: release
        #         uses: actions/create-release@v1
        #         with:
        #           draft: false
        #           prerelease: false
        #           release_name: ${{ github.ref }}-${{ github.sha }}
        #           tag_name: ${{ github.ref }}
        #         env:
        #           GITHUB_TOKEN: ${{ github.token }}
