name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: make build
      - name: version
        run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
        id: version
      - name: commit subjects
        id: commit_subjects
        run: |
          echo 'COMMITS<<EOF' >> $GITHUB_ENV
          git log --pretty=%s $(git describe \
            --abbrev=0 --tags 2> /dev/null ||
            git log --reverse --oneline --pretty=%h | head -n 1)..HEAD |
            xargs -r -n 1 -d '\n' echo \* >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          body: ${{ env.COMMITS }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
